"""initial

Revision ID: 3d3ba829b727
Revises: 
Create Date: 2023-11-06 16:00:30.209871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3d3ba829b727"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "category",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_category_id"), "category", ["id"], unique=False)
    op.create_table(
        "source",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_source_id"), "source", ["id"], unique=False)
    op.create_table(
        "supercategory",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_supercategory_id"), "supercategory", ["id"], unique=False)
    op.create_table(
        "text",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("body", sa.String(), nullable=False),
        sa.Column("link", sa.String(), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("supercategory_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["category.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["source.id"],
        ),
        sa.ForeignKeyConstraint(
            ["supercategory_id"],
            ["supercategory.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_text_category_id"), "text", ["category_id"], unique=False)
    op.create_index(op.f("ix_text_id"), "text", ["id"], unique=False)
    op.create_index(op.f("ix_text_source_id"), "text", ["source_id"], unique=False)
    op.create_index(
        op.f("ix_text_supercategory_id"), "text", ["supercategory_id"], unique=False
    )
    op.create_index(op.f("ix_text_title"), "text", ["title"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_text_title"), table_name="text")
    op.drop_index(op.f("ix_text_supercategory_id"), table_name="text")
    op.drop_index(op.f("ix_text_source_id"), table_name="text")
    op.drop_index(op.f("ix_text_id"), table_name="text")
    op.drop_index(op.f("ix_text_category_id"), table_name="text")
    op.drop_table("text")
    op.drop_index(op.f("ix_supercategory_id"), table_name="supercategory")
    op.drop_table("supercategory")
    op.drop_index(op.f("ix_source_id"), table_name="source")
    op.drop_table("source")
    op.drop_index(op.f("ix_category_id"), table_name="category")
    op.drop_table("category")
    # ### end Alembic commands ###
